### ISSUE TITLE
이슈가 아닌데 연락드려 죄송합니다 ㅜㅜ

### ISSUE THREAD

**Issue by Annadcin** [leechanee1/nodeinside#1]
promise는 처음 다루어봐서 잘 모르겠는데 혹시 예제소스 1개만 던져주실 수 있으신지요 ㅜㅜ
다음과 같은 코드를 사용했는데 session이 return이 안되네요ㅜㅜ

`let nodeinside = require('nodeinside');

nodeinside.init().then(() => {
	session = get_sess()
	console.log('세션');
	console.log(session);
}); //nodeinside 종료

function get_sess() {
	return Promise.resolve(nodeinside.session.login(user_id, user_pw));
}`

**Comment by leechanee1** [comment]
개인적 사용을 목적으로 만들었고 유지보수의 편리함을 위해 npm package로 publish 한거라
빈약한 설명이 뭇내 죄송하네요. nodeinside.session.login은 로그인 성공 시 session 을 resolve하여 반환합니다.

```
nodeinside.session.login('user_id', 'user_pw').then(session => {
    console.log(session); // session 반환.
});
```

시간이 바빠 아마 readme.md 를 수정할 시간이 없을 것 같네요. 즐코딩하세요
